spring.application.name=api-gateway
# Server Port
server.port=8080

# Gateway Routes - Profile Service
spring.cloud.gateway.routes[0].id=profile-service
spring.cloud.gateway.routes[0].uri=lb://PROFILE-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**, /api/profile/**