version: '3.8'

services:
  profile-service:
    build: .
    ports:
      - "9003:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/profile_db
      SPRING_DATASOURCE_USERNAME: collo
      SPRING_DATASOURCE_PASSWORD: Kipkirui92?

  mysql:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: profile_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
