# Server Port
server.port=8888

# Spring Cloud Config Server - Git Backend
spring.cloud.config.server.git.uri=https://github.com/cheruiyotcollins/banking-config-repospring.application.name=config-server
# Optional Git configurations
spring.cloud.config.server.git.search-paths=configs
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.timeout=5

# Security (if repo is private)
spring.cloud.config.server.git.username=your-github-username
spring.cloud.config.server.git.password=your-github-token